version: "3.7"

services:
  spring_boot:
    container_name: cpa_survey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/usr/src/app